### ISSUE TITLE
When will the paper be avaiable?

### ISSUE THREAD

**Issue by likanchuan** [zzpustc/CC-SAM#1]
Thanks for sharing your code! 

I guess your work would be insteresting and explore the important saddle-point issue in long recognition, as a further investigation beyond the prior work "Escaping Saddle Points for Effective Generalization on Class-Imbalanced Data.  NeurIPS 2022". I want to know when and where can I find your paper? I can'wait to read it.

Best wishes.

**Comment by zzpustc** [comment]
Hi，

Thanks for your interest in our paper. The official paper will only be released after the end of CVPR 2023, but we will upload a version on arXiv soon and remind you at that time.

Best

**Comment by likanchuan** [comment]
Thanks for your reply. Looking forward to your awesome work.
