### ISSUE TITLE
Results difference between the body of the paper and the appendix

### ISSUE THREAD

**Issue by likanchuan** [zzpustc/CC-SAM#5]
Hi! Thanks for sharing your excellent work! 

I notice there are different numbers between the main table in the body and the ablation study in the appendix under the same setting(is it?) e.g. CIFAR10-LT(beta: 100) 83.92 in Table 1 VS 82.42 in Table 2 in the Appendix. Did I miss something?  Looking forward to your reply!

**Comment by zzpustc** [comment]
Hi,

Apologies for any confusion caused. The discrepancy between the main text and the appendix arises from the request we received to apply strong augmentation to achieve state-of-the-art performance during the rebuttal phase. Consequently, we adhered to these suggestions. However, we also deemed it important to provide ablation studies without the implementation of strong data augmentation, hence their inclusion in the appendix.

Best

**Comment by likanchuan** [comment]
Thanks for your response! This makes sense to me.
