### ISSUE TITLE
Ask for a help with codes on large-scale datasets

### ISSUE THREAD

**Issue by AquuuuF** [zzpustc/CC-SAM#6]
Dear Authors,

I greatly appreciate the outstanding research presented in your paper. If it is not too much trouble, I was wondering if you would be willing to share the code you used for experiments on the large-scale datasets (ImageNet, Inatrulist2018, Places)? Thanks!

**Comment by zzpustc** [comment]
Hi,

Can you provide your email address so that I can send the code to you?

Best,
Zhipeng

**Comment by AquuuuF** [comment]
> Hi,
> 
> Can you provide your email address so that I can send the code to you?
> 
> Best, Zhipeng

Dear Zhipeng,

Very thanks for your help. Here is my email: Aquila_PYF@163.com. 

Sincerely,
Aq
